apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
    tier: front-end
spec:
  template:
    metadata:
      name: demo
      labels:
        app: my-app
        tier: front-end
    spec:
      containers:
        - name: demo-container
          image: nginx
  replicas: 3