apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-pod
  labels:
    app: my-app
    tier: front-end
spec:
  template:
    metadata:
      name: my-replica
      labels:
        app: mypod-replica
        tier: front-end
    spec:
      containers:
        - name: myapp-containers
          image: nginx
  replicas: 2
  selector:
    matchLabels:
        app: mypod-replica
        tier: front-end
#kubectl create secret docker-registry acrimage --docker-server=sysforedemo.azurecr.io --docker-username=sysforedemo --docker-password=rohmFyb4XgUW=zM4U+Ek6h4eUj1/Hpre --docker-email=manimaran.r@sysfore.com

