apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  namespace: qa
  labels:
    app: my-dep
    tier: front-end
spec:
  template:
    metadata:
      name: my-deployment
      labels:
        app: my-deploy
        tier: front-end
    spec:
      containers:
        - name: myapp-container
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy
      tier: front-end

#kubectl create -f Namespace-definition.yml to create new pod
#kubectl get pods -n qa