apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80            # Mandatory Field for SVC (port)
  selector:
    app: my-app
    tier: front-end


#kubectl get svc
#PORT range : 30000 - 32767
