apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: my-app
    tier: front-end
spec:
  containers:
    - name: demo-container
      image: nginx
      resources:
        requests:
          memory: "1Gi"
          cpu: 1
        limits:
          memory: "2Gi"
          cpu: 2