apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib
  labels:
    app: fib
spec:
  selector:
    matchLabels:
      app: fib
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
      - name: fib
        image: nginx
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        ports:
        - containerPort: 80