apiVersion: v1
kind: Service
metadata:
  name: myapp-service1
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80            # Mandatory Field for SVC (port)
  selector:
    app: fileshare-deployment

#kubectl get svc
#PORT range : 30000 - 32767
