apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib
  labels:
    app: fib
spec:
  selector:
    matchLabels:
      app: fib
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
      - name: fib
        image: manimaran/appmonitoring:36
  replicas: 20